name: gradproject
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  flutter_svg_provider: ^1.0.7
  flutter_screenutil: ^5.9.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/Pattern.svg
    - assets/images/Rounded_Pattern.svg
    - assets/images/Iconly/Bold/Arrow-Right-Square.svg
    - assets/images/Iconly/Bold/Category.svg
    - assets/images/Iconly/Bold/Chat.svg
    - assets/images/Iconly/Bold/Heart.svg
    - assets/images/Iconly/Bold/Home.svg
    - assets/images/Iconly/Bold/Profile.svg
    - assets/images/Iconly/Bold/Send.svg
    - assets/images/Iconly/Bold/Setting.svg
    - assets/images/Iconly/Bold/Tick-Square.svg
    - assets/images/Iconly/Bold/Notification.svg
    - assets/images/Iconly/Bulk/Category.svg
    - assets/images/Iconly/Bulk/Chat.svg
    - assets/images/Iconly/Bulk/Hide.svg
    - assets/images/Iconly/Bulk/Home.svg
    - assets/images/Iconly/Bulk/Notification.svg
    - assets/images/Iconly/Bulk/Search.svg
    - assets/images/Iconly/Bulk/Setting.svg
    - assets/images/Iconly/Bulk/Show.svg
    - assets/images/Iconly/Bulk/Tick-Square.svg
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist.ttf
